name: Deploy Supabase Migrations

on:
  push:
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/deploy-supabase.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_REF }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Link supabase project
        run: supabase link --project-ref $PROJECT_ID

      - name: Deploy migrations to Supabase
        run: supabase db push 